### ISSUE TITLE
Omit dependencies of omitted parents from report

### ISSUE THREAD

**Issue by sjamaan** [rm-hull/nvd-clojure#122]
When running `clj -Stree` in my project, I see many dependencies which are marked with an `X` which are `:superseded` and some of those have transitive dependencies marked as `:parent-omitted`. As I understand from [the (somewhat sparse) documentation](https://clojure.org/reference/dep_expansion#_tree_printing), that means the dependency is excluded, which means it shouldn't be active. Therefore, I think nvd-clojure is producing a false positive by printing such dependencies.

One example in my project is we're depending on two subprojects which both pull in `org.clojure/clojurescript`. One is old and pulls in a vulnerable version of `com.google.guava/guava`, but the other is newer and doesn't even depend on guava, it seems. Yet, guava is still flagged by nvd:

```
org.clojars.mmb90/cljs-cache 0.1.4
  X org.clojure/core.async 0.2.385 :superseded
    X org.clojure/tools.analyzer.jvm 0.6.10 :parent-omitted
  X org.clojure/clojurescript 1.9.89 :superseded
    . com.google.javascript/closure-compiler v20160315
      X com.google.javascript/closure-compiler-externs v20160315 :parent-omitted
      X args4j/args4j 2.0.26 :parent-omitted
      X com.google.guava/guava 19.0 :parent-omitted
      X com.google.protobuf/protobuf-java 2.5.0 :parent-omitted
      X com.google.code.gson/gson 2.2.4 :parent-omitted
      X com.google.code.findbugs/jsr305 1.3.9 :parent-omitted
    . org.clojure/google-closure-library 0.0-20160609-f42b4a24
      X org.clojure/google-closure-library-third-party 0.0-20160609-f42b4a24 :parent-omitted
    . org.clojure/data.json 0.2.6
    . org.mozilla/rhino 1.7R5
    X org.clojure/tools.reader 1.0.0-beta1 :superseded
  . adzerk/boot-test 1.1.2
  . crisptrutski/boot-cljs-test 0.2.2-20160402.204547-3
  . tailrecursion/cljs-priority-map 1.2.1
    X org.clojure/clojurescript 1.7.170 :older-version
 . <other package>
   . <nested other package>
    . org.clojure/clojurescript 1.10.866 :newer-version
      . com.google.javascript/closure-compiler-unshaded v20210505
      . org.clojure/google-closure-library 0.0-20201211-3e6c510d
        . org.clojure/google-closure-library-third-party 0.0-20201211-3e6c510d
      . org.clojure/data.json 0.2.6
      X org.clojure/tools.reader 1.3.3 :older-version
      . com.cognitect/transit-clj 0.8.309
        . com.cognitect/transit-java 0.8.332
          X com.fasterxml.jackson.core/jackson-core 2.8.7 :older-version
          . org.msgpack/msgpack 0.6.12
            . com.googlecode.json-simple/json-simple 1.1.1
            . org.javassist/javassist 3.18.1-GA
          X commons-codec/commons-codec 1.10 :older-version

```

A minimal reproduction `deps.edn` case where guava is included (but should not be) is as follows:

```
{:deps {org.clojars.mmb90/cljs-cache {:mvn/version "0.1.4"}
        rewrite-cljs/rewrite-cljs {:mvn/version "0.4.5"}}

 :aliases {:nvd {:extra-deps {nvd-clojure/nvd-clojure {:mvn/version "2.1.0"}}
                 :main-opts ["-m" "nvd.task.check"]}}}
```

The funny thing, is that with this particular `deps.edn`, the `-Stree` output doesn't even *mention* guava! However, it *is* included in the `nvd` vulnerability report...

**Comment by vemv** [comment]
Hi, thank you for using nvd-clojure.

Are you following https://github.com/rm-hull/nvd-clojure/tree/93a17adf241641813e931e996bc1069e50620719#clojure-cli carefully? It describes using a classpath _as computed by_ `clojure`.

It doesn't make up transitive dependencies - it will analyze exactly what you give to it.

**Comment by sjamaan** [comment]
Thanks, I was not paying close enough attention I think - the guava version listed as vulnerable is the new one, which the active closure compiler depends on. I think the real issue here is that `-Stree` isn't listing it!
