### ISSUE TITLE
2.6.0 release

### ISSUE THREAD

**Issue by MIJOTHY** [rm-hull/nvd-clojure#144]
I was looking to see if https://github.com/rm-hull/nvd-clojure/commit/7e4609454e05c3fee5d6cbe1765c073c78c14159 (the dependency-check update) has been included in any releases, and I couldn't see any see `2.6.0` commits on master. I do see [a commit](https://github.com/rm-hull/nvd-clojure/commit/100856191cdf1ec0b630768235eb99fc14ee568a) on the dev branch, is this absence of `2.6.0` on master intentional?

**Comment by vemv** [comment]
https://github.com/rm-hull/nvd-clojure/releases/tag/v2.6.0 exists and will be visible into master soon.

Cheers - V
