### ISSUE TITLE
Easier template/setup

### ISSUE THREAD

**Issue by slipset** [rm-hull/nvd-clojure#151]
### Description

Having just set up nvd-clojure for https://github.com/clj-commons/clj-yaml, here's some improvements that I'd love to see:
The project.clj/deps.edn file for the separate project are fairly static and could available as a download. 
Further more, the incantations to run nvd-clojure could be encapsulated in scripts as in:
```sh
#!/bin/sh
lein with-profile -user run -m nvd.task.check "config.json" "$(cd ..; lein with-profile -user,-dev classpath)"
```
for lein.
Note also that I've added the `config.json` which could also be included by default.
the `config.json` could look something like this:
```json
{"delete-config?": false,
 "nvd": {"suppression-file": "./suppressions.xml",
         "data-directory": ".nvd-cache/"}}
```
And finally, a `suppressions.xml` which could look like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd">
  <!-- You can find examples in https://jeremylong.github.io/DependencyCheck/general/suppression.html -->
</suppressions>
```
So, basically, I'm advocating for a bundle which contains:
```
$ tree ./nvd
./nvd
├── README.md
├── config.json
├── deps.edn
├── deps.sh
├── lein.sh
├── project.clj
└── suppressions.xml
```
which the user is advised to install at the top-level in their project, so they could run eg
```sh
$ ./nvd/deps.sh
```

### Version

2.9.0

### Java version

```shell
not applicable
```

### Installation compliance

- [X] I have read again and made sure that I'm following **exactly** the instructions for my tool of choice ([Leiningen](https://github.com/rm-hull/nvd-clojure/tree/v2.9.0#leiningen), [Clojure CLI](https://github.com/rm-hull/nvd-clojure/tree/v2.9.0#clojure-cli), [Clojure CLI Tool](https://github.com/rm-hull/nvd-clojure/tree/v2.9.0#clojure-cli-tool)).
- [X] I understand that false positives [can be skipped locally](https://github.com/rm-hull/nvd-clojure/tree/v2.9.0#configuration-options) and should be reported to [DependencyCheck](https://github.com/jeremylong/DependencyCheck).

**Comment by vemv** [comment]
> The project.clj/deps.edn file for the separate project are fairly static and could available as a download.

It's just a very tiny file tbh. By not offering a free-form download, we are encouraging users to create an actual separate directory, which translates into an [isolated classpath](https://github.com/rm-hull/nvd-clojure/tree/v2.9.0#avoiding-classpath-interference) which is a crucial requisite.

> Further more, the incantations to run nvd-clojure could be encapsulated in scripts as in:

There are a couple cons:

* we cannot, must not, guess which profiles/aliases should be activated
* instructing people to run scripts isn't on par IMO with a security-oriented project. lein/clojure commands can be _understood_. Just like one doesn't provide a script for `lein test`.

> Note also that I've added the config.json which could also be included by default.

This is jotted down in https://github.com/rm-hull/nvd-clojure/issues/125 . Let me know if you'd like to pick it up!

> So, basically, I'm advocating for a bundle which contains:

I'm not a huge fan of bundles, uberjars, GH-releases _for a security project_. Everything should be simple, transparent, auditable.

The ultimate 'bundle' is a simple git clone which you are certainly invited to perform when desired! That's as auditable as things can get.

Hope this is a good explanation!

Cheers - V
