### ISSUE TITLE
Make NVD API key optional

### ISSUE THREAD

**Issue by DerGuteMoritz** [rm-hull/nvd-clojure#176]
### Description

According to [DependencyCheck's upgrade notice](https://github.com/jeremylong/DependencyCheck#900-upgrade-notice), providing an NVD API key is not required but (only) highly recommended. That is to say, the NVD API can still be used without an API key (albeit with some restrictions). However, `nvd-clojure` requires providing a key. Since registering for a key incurs some organizational overhead, it would be nice to be able to use the public API in the meantime. In other words: Make the API key optional on `nvd-clojure`'s end, as well.

### Version

4.0.0

### Java version

```shell
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-nixos)
OpenJDK 64-Bit Server VM (build 17.0.7+7-nixos, mixed mode, sharing)
```

### Installation compliance

- [X] I have read again and made sure that I'm following **exactly** the instructions for my tool of choice ([Leiningen](https://github.com/rm-hull/nvd-clojure/tree/v4.0.0#leiningen), [Clojure CLI](https://github.com/rm-hull/nvd-clojure/tree/v4.0.0#clojure-cli), [Clojure CLI Tool](https://github.com/rm-hull/nvd-clojure/tree/v4.0.0#clojure-cli-tool)).
- [X] I understand that false positives [can be skipped locally](https://github.com/rm-hull/nvd-clojure/tree/v4.0.0#configuration-options) and should be reported to [DependencyCheck](https://github.com/jeremylong/DependencyCheck).

**Comment by vemv** [comment]
Thanks for a sensible issue/suggestion.

I don't think it's in the best interest of any involved part to keep fostering a slower, issue-prone code path.

The `organizational overhead` is minimal as obtaining a key requires providing no PII at all. The key you will instantly receive is more akin to a user ID than to a password - therefore if it's any trouble to keep it secret for CI, I'd consider it safe to check into version control.

**Comment by DerGuteMoritz** [comment]
By organizational overhead I was mainly referring to the terms of use one has to accept for creating an account. For example, they state:

> Services which utilize or access the NVD API are asked to display the following notice prominently within the application: "This product uses the NVD API but is not endorsed or certified by the NVD."

Not 100% sure what is implied by this and since I am not a lawyer, I'd either have to clear this with my legal department or have somebody higher up the chain check this off and accept the risk of not fully grokking the implications. 

In any case, it's not important to me anymore since we've since figured it out and registered an account :smile: Feel free to close.

**Comment by vemv** [comment]
> Services which utilize or access the NVD API are asked to display the following notice prominently within the application: "This product uses the NVD API but is not endorsed or certified by the NVD."

Most likely this refers to libraries/services which sole purpose is performing NVD-based checks. 

Note that a production app does not package NVD in any way - it usage is typically limited to a build-time check.

Cheers - V
