### ISSUE TITLE
Support fail-threshold as a command line argument

### ISSUE THREAD

**Issue by sann3** [rm-hull/nvd-clojure#23]
Is it possible to add fail-threshold as a command line argument

**Comment by bostonaholic** [comment]
I would also appreciate this feature to make scripting simpler.

Maybe as an environment variable, `NVD_FAIL_THRESHOLD`?

**Comment by vemv** [comment]
This has been fixed since, see https://github.com/rm-hull/nvd-clojure#configuration-options

Cheers - V
