### ISSUE TITLE
Leiningen plugin does not play nicely with `lein monolith`

### ISSUE THREAD

**Issue by rymndhng** [rm-hull/nvd-clojure#50]
Hey there, I'm trying to run this across multiple project.clj files using `lein monolith each`.

I noticed that `check` calls `(System/exit ..)` by default, which prevents `lein monolith` from executing the checks on each repository. 

Is it possible to configure the exit behavior to throw an exception instead of calling System/exit?

Note: I also tried to set `:nvd {:exit-after-check false}` in my project.clj file, but it had no effect.

**Comment by vemv** [comment]
I'm guessing that one should use ` leiningen.core.main/exit` over `System/exit` if the former is available

It's what's being done in e.g. https://github.com/jonase/eastwood/blob/1b87b1f377052116f57c2b62b2f0e97669d91551/src/eastwood/exit.clj , worked well for a similar problem

**Comment by vemv** [comment]
1.7.0 is out, featuring a new `:throw-if-check-unsuccessful?` option. It's reflected in the README and you can also refer to the integration test in 727f023be017b59599b57405bf599f0cef49276f . 

Hope it helps you!

Cheers - V
