### ISSUE TITLE
IlllegalArgumentException when running the from the CLI

### ISSUE THREAD

**Issue by vamem9z-Moses** [rm-hull/nvd-clojure#74]
The error occurred during the first run of the program. I'm running OpenJDK 11. See the full version description below.

To Reproduce 

 1. Add  to deps.end
            :nvd {:extra-deps {lein-nvd/lein-nvd {:mvn/version "1.4.1"}}
                  :main-opts ["-m" "nvd.task.check"]}}}

2. Run clj -M:nvd
3. See error:
    Execution error (IllegalArgumentException) at nvd.task.check/make-classpath (check.clj:66).
    No matching field found: getURLs for class jdk.internal.loader.ClassLoaders$AppClassLoader

Java version:

openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode)

**Comment by vemv** [comment]
This project's original deps.edn-oriented API, while sensible, makes some guess work at figuring out the classpath.

I'd recommend to try out https://github.com/rm-hull/lein-nvd#avoiding-classpath-interference instead. Would love to hear an experience report.

Cheers - V
